### ISSUE TITLE
ReferenceError: rgba is not defined

### ISSUE THREAD

**Issue by atoav** [lrsjng/pagemap#3]
When I try to use the demo (text.html) with the init code from the example:

```javascript
pagemap(document.querySelector('#map'), {
    viewport: null,
    styles: {
        'header,footer,section,article': rgba(0,0,0,0.08),
        'h1,a': rgba(0,0,0,0.10),
        'h2,h3,h4': rgba(0,0,0,0.08)
    },
    back: rgba(0,0,0,0.02),
    view: rgba(0,0,0,0.05),
    drag: rgba(0,0,0,0.10),
    interval: null
});
```
my console throws a `ReferenceError: rgba is not defined`  

If I use the simpler init code from the text demo this doesn't happen:
```javascript
pagemap(document.querySelector('#map'));
```

Maybe I just overlooked something – any pointers? Are there possible dependencies?

On a different topic: I had a hard time finding out that pagemap needs to be imported at bottom, maybe you could add a hint in the readme to avoid other people the hassle.

**Comment by atoav** [comment]
Found the source of the Error – the color definitions need to be wrapped in paranthesis like so:
```javascript
pagemap(document.querySelector('#map'), {
    viewport: null,
    styles: {
        'header,footer,section,article': 'rgba(0,0,0,0.08)',
        'h1,a': 'rgba(0,0,0,0.10)',
        'h2,h3,h4': 'rgba(0,0,0,0.08)'
    },
    back: 'rgba(0,0,0,0.02)',
    view: 'rgba(0,0,0,0.05)',
    drag: 'rgba(0,0,0,0.10)',
    interval: null
});
```
This resolved the issues I had.

**Comment by peterkos** [comment]
Small correction -- they need to be wrapped in _quotes_, not parenthesis.

**Comment by adriantoll** [comment]
@lrsjng This needs to be updated on the website: https://larsjung.de/pagemap/
