### ISSUE TITLE
Cannot read property 'style' of null

### ISSUE THREAD

**Issue by vishvega** [lrsjng/pagemap#5]
I've initiated pagemap as your instructions. and it's showing and all. but whenever I try to click on it and drag (like you do with scrollbar), it doesn't work as demo page and throws an error into console.

```
pagemap0.4.0.min.js:2 Uncaught TypeError: Cannot read property 'style' of null
    at HTMLCanvasElement.j (pagemap0.4.0.min.js:2)
j @ pagemap0.4.0.min.js:2
```
What would be the issue here and how can I fix it?
Im using wordpress and I've put map canvas like below

```
<canvas id='map'></canvas>
		<?php
		global $post;
		$pageId = $post->ID; 
		$post = get_post($pageId); 
		$content = apply_filters('the_content', $post->post_content); 
		echo $content;  
		?>
``` 
Is there any way to fix this?
also I included pagemap js before my custom js file and before jquery (if this helps)

**Comment by stitch** [comment]
The pagemap script should load after the body has loaded it seems. What works is to place the script at the bottom of the page, so that  document.querySelector('body') in the script returns something. You'll see that body is null when setting a breakpoint on i.
